CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);
/*NO COMANDO ACIMA O ID RECEBE A CLAUSA 'PRIMARY KEY' COM O ARGUMENTO 'AUTO_INCREMENT'*/
/*PK - SERA O INDEX*/
/*AUTO - INDICA QUE O BANCO IRA GERÁ CADA ID AUTOMATICAMENTE*/
/*VALORES QUE SAO OBRIGATORIOS RECEBEM A CLAUSULA 'NOT NULL'*/
/*SEXO TEVE SUAS ENTRADAS LIMITADAS PELO ENUM*/
/*EMAIL/CPF RECEBE A CLAUSULA 'UNIQUE' PELO SIMPLES FATO DE NAO EXISTIR DOIS EMAILS COM MESMO ENDEREÇO*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CELL'),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
/*LEMBRANDO, ID_CLIENTE EH UNICO PQ A RELAÇAO ENTRE CLIENTE E ENDEREÇO EH 1x1*/
/*AS RELAÇÕES PRESENTES NO DER SAO REPRESENTADAS PELAS 'FK - FOREIGN KEY' NO MODELO FISICO*/
/*FK NADA MAIS É DO QUE A PK DE UMA TABELA REFERENCIADA EM OUTRA TABELA*/

/*PUXANDO DADOS DE VARIAS TABELAS*/
SELECT NOME, SEXO, BAIRRO, CIDADE, NOW() AS 'DATA'
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

/*EXEMPLO DE JOIN*/
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE INNER JOIN ENDERECO ON IDCLIENTE = ID_CLIENTE;

/*JOIN COM MAIS DE DUAS TABELAS*/
/*CODIGO ABAIXO NAO FUNCIONA POR HAVER CAMPOS IGUAIS (SE NAO FOSSE POR ISSO IRIA FUNCIONAR)*/
SELECT NOME, SEXO, BAIRRO, CIDADE, NUMERO
FROM CLIENTE
INNER JOIN ENDERECO 
ON IDCLIENTE = ID_CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;

/*JEITO CORRETO PARA ACABAR COM AS DUPLICATAS*/
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/*EH POSSIVEL CRIAR APELIDOS PARA FACILITAR*/
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY E.BAIRRO;
/*ORDENAÇAO POR PARAMETRO*/