
/*6-a*/
SELECT E.NUMERO_SERIE, E.DESCRICAO, A.NOME, P.NOME
FROM PLANTAS P
INNER JOIN AREAS A 
ON P.ID_PLANTA = A.IDPLANTA
INNER JOIN EQUIPAMENTOS E 
ON A.ID_AREA = E.IDAREA;

/*PK sem AUTO_INCREMENT*/
INSERT INTO PLANTAS VALUES(45,'Teste_planta_1');
INSERT INTO AREAS VALUES(1,'TESTE_AREA1',45);