CREATE DATABASE JOSE2;

USE JOSE2;

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	DONO VARCHAR(30) NOT NULL,
	MARCA VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL'),
	DDD INT(2),
	NUMERO VARCHAR(9),
	ID_CARRO INT,
	FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO)
);

CREATE TABLE CORES(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO),
	ID_COR INT,
	FOREIGN KEY(ID_COR) REFERENCES CORES(IDCOR),
	PRIMARY KEY(ID_CARRO, ID_COR)
);

INSERT INTO CARRO VALUES(NULL,'TULIO','GOL');
INSERT INTO CARRO VALUES(NULL,'LETICIA','PALIO');

INSERT INTO TELEFONE VALUES(NULL,'CEL',31,'992687974',1);
INSERT INTO TELEFONE VALUES(NULL,'RES',31,'34340960',2);

INSERT INTO CORES VALUES(NULL,'VERMELHO');
INSERT INTO CORES VALUES(NULL,'AZUL');
INSERT INTO CORES VALUES(NULL,'PRETO');

INSERT INTO CARRO_COR VALUES(1,1);
INSERT INTO CARRO_COR VALUES(1,3);
INSERT INTO CARRO_COR VALUES(2,2);
INSERT INTO CARRO_COR VALUES(2,3);

