CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	CPF VARCHAR(15) UNIQUE,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	NOME VARCHAR(30) NOT NULL
);
/*NO COMANDO ACIMA O ID RECEBE A CLAUSA 'PRIMARY KEY' COM O ARGUMENTO 'AUTO_INCREMENT'*/
/*PK - SERA O INDEX*/
/*AUTO - INDICA QUE O BANCO IRA GERÁ CADA ID AUTOMATICAMENTE*/
/*VALORES QUE SAO OBRIGATORIOS RECEBEM A CLAUSULA 'NOT NULL'*/
/*SEXO TEVE SUAS ENTRADAS LIMITADAS PELO ENUM*/
/*EMAIL/CPF RECEBE A CLAUSULA 'UNIQUE' PELO SIMPLES FATO DE NAO EXISTIR DOIS EMAILS COM MESMO ENDEREÇO*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CELL'),
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
/*LEMBRANDO, ID_CLIENTE EH UNICO PQ A RELAÇAO ENTRE CLIENTE E ENDEREÇO EH 1x1*/
/*AS RELAÇÕES PRESENTES NO DER SAO REPRESENTADAS PELAS 'FK - FOREIGN KEY' NO MODELO FISICO*/
/*FK NADA MAIS É DO QUE A PK DE UMA TABELA REFERENCIADA EM OUTRA TABELA*/
